# Generated by Django 2.0.1 on 2020-06-15 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.FileField(max_length=50, upload_to='', verbose_name='用户名')),
                ('password', models.IntegerField(max_length=50, verbose_name='密码')),
                ('status', models.CharField(blank=True, choices=[('D', '未开始'), ('R', '运行中'), ('W', '成功'), ('S', '失败')], default='D', max_length=10, verbose_name='状态')),
                ('type', models.CharField(blank=True, choices=[('S', '完成'), ('D', '待处理'), ('F', '取消')], default='D', max_length=10, null=True, verbose_name='进度')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户记录',
                'verbose_name_plural': '用户记录',
            },
        ),
    ]
