# Generated by Django 2.0.1 on 2020-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name='延迟间隔')),
            ],
            options={
                'verbose_name': '延迟间隔设置',
                'verbose_name_plural': '延迟间隔设置',
            },
        ),
    ]
