# Generated by Django 2.0.1 on 2020-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_settings_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='正确率'),
        ),
    ]
