# Generated by Django 2.0.1 on 2020-06-15 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdata_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(max_length=50, upload_to='', verbose_name='姓名')),
                ('kecheng', models.FileField(max_length=50, upload_to='', verbose_name='课程')),
                ('timu', models.FileField(upload_to='', verbose_name='测试题目')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='分数')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
            },
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.FileField(max_length=50, null=True, upload_to='', verbose_name='姓名'),
        ),
    ]
