# Generated by Django 2.0.1 on 2020-06-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200616_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=56, verbose_name='用户名')),
                ('password', models.CharField(max_length=56, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='settings',
            name='accuracy',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='正确率'),
        ),
    ]
