# Generated by Django 2.0.1 on 2020-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200616_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='accuracy',
            field=models.IntegerField(null=True, verbose_name='正确率'),
        ),
    ]
