# Generated by Django 2.2.1 on 2020-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200616_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timu_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(max_length=255, upload_to='', verbose_name='题目')),
                ('answer', models.FileField(max_length=255, upload_to='', verbose_name='答案')),
            ],
            options={
                'verbose_name': '答案记录',
                'verbose_name_plural': '答案记录',
            },
        ),
    ]
