# Generated by Django 2.2.1 on 2020-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_timu_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='score',
            field=models.FileField(null=True, upload_to='', verbose_name='分数'),
        ),
    ]
