# Generated by Django 2.2.1 on 2020-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200616_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(blank=True, choices=[('T', '测试'), ('S', '视频')], max_length=10, verbose_name='类型'),
        ),
    ]
