# Generated by Django 2.2.1 on 2020-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200616_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='create_dt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='创建时间'),
        ),
    ]
