# Generated by Django 2.2.1 on 2020-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200616_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='用户名'),
        ),
    ]
