# Generated by Django 2.2.1 on 2020-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_logs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(blank=True, choices=[('T', '测试'), ('S', '视频'), ('J', '记录')], max_length=10, verbose_name='类型'),
        ),
    ]
