# Generated by Django 2.2.1 on 2020-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200618_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='loginUser',
            field=models.CharField(default='test', max_length=50, null=True, verbose_name='导入用户'),
        ),
    ]
