# Generated by Django 2.2.1 on 2020-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userdata_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(blank=True, choices=[('T', '测试'), ('S', '视频'), ('J', '记录'), ('C', '成绩')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='loginUser',
            field=models.CharField(max_length=50, null=True, verbose_name='导入用户'),
        ),
    ]
